const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('writingWorkbench', {
  getWorkspaceState: () => ipcRenderer.invoke('workspace:get-state'),
  chooseLibraryDirectory: () => ipcRenderer.invoke('workspace:choose-library-directory'),
  scanLibrary: () => ipcRenderer.invoke('workspace:scan-library'),
  createBook: (input) => ipcRenderer.invoke('workspace:create-book', input),
  deleteBook: (bookPath) => ipcRenderer.invoke('workspace:delete-book', bookPath),
  generatePlanningQuestion: (input) => ipcRenderer.invoke('planning:next-question', input),
  generateProjectPackage: (input) => ipcRenderer.invoke('planning:generate-project-package', input),
  openBook: (bookPath) => ipcRenderer.invoke('book:open', bookPath),
  openChapter: (bookPath, chapterFile) => ipcRenderer.invoke('book:open-chapter', { bookPath, chapterFile }),
  createChapter: (input) => ipcRenderer.invoke('book:create-chapter', input),
  saveChapter: (input) => ipcRenderer.invoke('book:save-chapter', input),
  listChapterSnapshots: (input) => ipcRenderer.invoke('book:list-chapter-snapshots', input),
  restoreChapterSnapshot: (input) => ipcRenderer.invoke('book:restore-chapter-snapshot', input),
  applyCandidate: (input) => ipcRenderer.invoke('book:apply-candidate', input),
  applyWritingCandidate: (input) => ipcRenderer.invoke('book:apply-writing-candidate', input),
  listProjectMaterials: (input) => ipcRenderer.invoke('book:list-project-materials', input),
  readProjectMaterial: (input) => ipcRenderer.invoke('book:read-project-material', input),
  saveProjectMaterial: (input) => ipcRenderer.invoke('book:save-project-material', input),
  listProjectMaterialSnapshots: (input) => ipcRenderer.invoke('book:list-project-material-snapshots', input),
  restoreProjectMaterialSnapshot: (input) => ipcRenderer.invoke('book:restore-project-material-snapshot', input),
  applyContextSync: (input) => ipcRenderer.invoke('book:apply-context-sync', input),
  generateAiEditCandidate: (input) => ipcRenderer.invoke('book:generate-ai-edit-candidate', input),
  startNextChapterFlow: (input) => ipcRenderer.invoke('book:start-next-chapter-flow', input),
  startBatchWritingFlow: (input) => ipcRenderer.invoke('book:start-batch-writing-flow', input),
  getLatestWritingTaskRun: (input) => ipcRenderer.invoke('book:get-latest-writing-task-run', input),
  retryWritingTaskStep: (input) => ipcRenderer.invoke('book:retry-writing-task-step', input),
  generateChapterFeedbackPackage: (input) => ipcRenderer.invoke('book:generate-chapter-feedback-package', input),
  organizeProject: (bookPath) => ipcRenderer.invoke('book:organize-project', bookPath),
  exportChapter: (input) => ipcRenderer.invoke('book:export-chapter', input),
  exportBook: (bookPath) => ipcRenderer.invoke('book:export-book', bookPath),
  openPath: (targetPath) => ipcRenderer.invoke('shell:open-path', targetPath),
  getAiSettings: () => ipcRenderer.invoke('ai:get-settings'),
  getAiCallLogs: () => ipcRenderer.invoke('ai:get-call-logs'),
  listAiProfiles: () => ipcRenderer.invoke('ai:list-profiles'),
  useAiProfile: (profileId) => ipcRenderer.invoke('ai:use-profile', profileId),
  deleteAiProfile: (profileId) => ipcRenderer.invoke('ai:delete-profile', profileId),
  saveAiSettings: (input) => ipcRenderer.invoke('ai:save-settings', input),
  testAiConnection: (input) => ipcRenderer.invoke('ai:test-connection', input),
  cancelAiRequest: (requestId) => ipcRenderer.invoke('ai:cancel-request', requestId),
  onAiTaskProgress: (callback) => {
    const listener = (_event, payload) => callback(payload)
    ipcRenderer.on('ai:task-progress', listener)
    return () => ipcRenderer.removeListener('ai:task-progress', listener)
  },
  generateCheckSyncCandidate: (input) => ipcRenderer.invoke('book:generate-check-sync-candidate', input),
  generateOutlineCandidate: (input) => ipcRenderer.invoke('book:generate-outline-candidate', input),
  listChapterOutlineIndex: (input) => ipcRenderer.invoke('book:list-chapter-outline-index', input),
  generateSingleChapterOutline: (input) => ipcRenderer.invoke('book:generate-single-chapter-outline', input),
  batchGenerateChapterOutlines: (input) => ipcRenderer.invoke('book:batch-generate-chapter-outlines', input),
  generateMaterialCandidate: (input) => ipcRenderer.invoke('book:generate-material-candidate', input),
  projectChat: (input) => ipcRenderer.invoke('book:project-chat', input),
  generateProjectUpdatePackage: (input) => ipcRenderer.invoke('book:generate-project-update-package', input),
  generateProjectRepairPackage: (input) => ipcRenderer.invoke('book:generate-project-repair-package', input),
  generateSmartFeedbackPackage: (input) => ipcRenderer.invoke('book:generate-smart-feedback-package', input),
  applyProjectUpdatePackage: (input) => ipcRenderer.invoke('book:apply-project-update-package', input),
  compactProjectMemory: (input) => ipcRenderer.invoke('book:compact-project-memory', input),
})
